# DarkBrowser — i2pd config
[httpproxy]
enabled = true
address = 127.0.0.1
port = 4444

[ntcp2]
enabled = true

[sam]
enabled = false

[bobproxy]
enabled = false

[i2cp]
enabled = false

[logging]
destination = stdout
level = info

[upnp]
enabled = false

[reseed]
verify = true
